export const ADD_TO_ORDER = 'ADD_PRODUCT_TO_ORDER';
export const REMOVE_FROM_ORDER = 'REMOVE_PRODUCT_FROM_ORDER';
export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const GET_SHOPS = 'GET_SHOPS';
export const GET_SHOP_PRODUCTS = 'GET_SHOP_PRODUCTS';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_COURIERS = 'GET_COURIERS';
